services:
  - type: web
    plan: pro
    name: django-app

    runtime: python
    repo: https://github.com/rkoron007/django.git
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-app-db
          property: connectionString

databases:
  - name: django-app-db
    plan: free
previews:
  generation: automatic
